[package]
name = "ename_engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
avian3d.workspace = true
bevy.workspace = true
big_space.workspace = true
ename_asset_alias.workspace = true
ename_asset_content.workspace = true
ron.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
