[package]
name = "ename_xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Command line tooling for the content pipeline: check, fix, list, move."

[dependencies]
dirs = { workspace = true }
ename_asset_alias = { workspace = true, default-features = false }
ename_asset_package = { workspace = true, default-features = false }
futures-lite = { workspace = true }

[lints]
workspace = true
