[package]
name = "example_game_lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true }
ename_engine = { workspace = true }

[dev-dependencies]
ename_asset_content = { workspace = true }

[lints]
workspace = true
