[package]
name = "game"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["dev"]
# Development-only Bevy features. Must be off for a shipping build.
dev = ["bevy/dynamic_linking", "bevy/dev"]

[dependencies]
bevy = { workspace = true }
engine = { workspace = true }

[lints]
workspace = true
